--changeset CREATE_TABLE_RENT_BOOK

CREATE TABLE IF NOT EXISTS lib.RENTBOOK
(

    ID SERIAL unique,
    STARTDATE DATE,
    ENDDATE DATE,
    BOOK_ID integer,

    CONSTRAINT BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES lib.BOOK (ID)
)