--changeset CREATE_TABLE_RENT_BOOK
DROP TABLE IF EXISTS lib.RENTBOOK cascade;

CREATE TABLE IF NOT EXISTS lib.RENTBOOK
(

    ID SERIAL unique,
    START_DATE DATE,
    END_DATE DATE,
    BOOK_ID integer,
    STUDENT_ID integer,

    CONSTRAINT BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES lib.BOOK (ID)
)
